# Generated by Django 3.1 on 2020-09-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='option1',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='Questions',
            field=models.ImageField(default='', upload_to='home/images1'),
        ),
    ]
