# Generated by Django 3.1 on 2020-09-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200909_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='option1',
            field=models.CharField(default='', max_length=100),
        ),
    ]
