# Generated by Django 3.1 on 2020-09-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_quiz_option1'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='Question_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
