# Generated by Django 3.1 on 2020-09-09 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_quiz_question_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='Question_id',
        ),
    ]
