# Generated by Django 3.1 on 2020-09-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_quiz_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='questionNO',
            field=models.CharField(default='', max_length=100),
        ),
    ]
