# Generated by Django 3.1 on 2020-10-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_exam_hs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videofile', models.FileField(default='', upload_to='home/videos1')),
                ('heading', models.CharField(default='', max_length=100)),
                ('supportimages', models.ImageField(default='', upload_to='home/images3')),
                ('contentNO', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
