# Generated by Django 3.1 on 2020-10-10 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='videofile',
        ),
    ]
