# Generated by Django 3.1 on 2020-10-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_item_videofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='contentvedio',
            field=models.FileField(default='', upload_to='home/videos1'),
        ),
    ]
